on:
  push:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install package
        run: pip install -e '.[dev]'
      - name: Check mypy
        run: mypy .
      - name: Check black
        run: black --check .
      - name: Check isort
        run: isort --check .

  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install package
        run: pip install -e .
      - name: Demo click
        run: bash demo.sh click
      - name: Demo argparse
        run: bash demo.sh argparse
